name: Sync Docker Images
run-name: Sync ${{ inputs.source_repo }} to ${{ inputs.destination_scope }}
on: 
  workflow_dispatch:
    inputs:
      repo:
        description: '仓库 (格式 repo)'
        required: true
        default: ''


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4        
      -
        name: Login to GitLab
        uses: docker/login-action@v3
        with:
          registry: registry.ap-southeast-1.aliyuncs.com
          username: 2457395722@qq.com
          password: ${{ secrets.DOCKER_PASS }}

      - name: Run for ${{ github.event.inputs.repo }}
        env:
          REPO: ${{ github.event.inputs.repo }}
        run: |
            chmod +x sync-my.sh

            ./sync-my.sh
